### PR TITLE
Add pass/fail message to the body of the email

### PR DESCRIPTION
**Pull request by jakirkham**

### CODE REVIEW

**Comment by flenter** [comment]
Thank you for this pr. 

Unfortunately the message will now always state that it's a build that's passing/failing. This step can also be executed during a deploy. 

There's an environment variable `DEPLOY` that's set if it's a deploy. See also: http://devcenter.wercker.com/docs/environment-variables/available-env-vars.html and https://github.com/jakirkham/step-email-notify/blob/pass_fail_body/run.sh#L59-L64 where it's also used.

**Comment by jakirkham** [comment]
@flenter, is this more what you are looking for?

**Comment by jakirkham** [comment]
@flenter, made some changes and squashed them for simplicity. It will not change the message during deploy. Getting the build status has been simplified.

**Comment by jakirkham** [comment]
Any more thoughts on this?

**Comment by flenter** [comment]
looks good to me, thank you!

**Comment by flenter** [comment]
I'll release the step (as version 1.1.0) after https://github.com/wercker/step-email-notify/pull/3 has been merged in. That pr adds support for the result message for deploys (and bumps the version to 1.1.0).

**Comment by jakirkham** [comment]
Thanks. Ok.

**Pull request merged**
